version: '3'
services:
  es_cluster:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: es_cluster
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    networks:
      - elastic_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    depends_on:
      - es_cluster
    environment:
      - ELASTICSEARCH_HOSTS=http://es_cluster:9200
    ports:
      - 5601:5601
    networks:
      - elastic_network

networks:
  elastic_network:
